import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/nav-bar";
import Footer from "@/components/footer";
import AuthProvider from "@/provider/auth-provider";
import CartProvider from "@/provider/cart-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GBuy",
  description: "Generated by create next app",
};
console.log(inter.className);
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={inter.className}>
          <AuthProvider>
            {/* <CartProvider> */}
            <Navbar />
            {children}
            <Footer />
            {/* </CartProvider> */}
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
